# Numpy Exercises
***
1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this [link](https://www.theanalysisfactor.com/centering-and-standardizing-predictors/) for more on centering.

7. Calculate the z-score for each data point.
***

In [2]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. ### How many negative numbers are there?


In [3]:
# cave person approach
is_negative = np.array([False, False, False, False, True, True, False, False, False, True, False, True])
print(a[is_negative])
len(a[is_negative])

(a < 0).sum()
                    

[-2 -1 -6 -7]


4

In [115]:
is_negative = a < 0
print(a[is_negative])
len(a[is_negative])

[-2 -1 -6 -7]


4

2. ### How many positive numbers are there?

In [117]:
is_positive = a > 0
print(a[is_positive])
len(a[is_positive])
# examining them separately for the first two runs, although print and len can be used together

len(a[a > 0])

[ 4 10 12 23  3]


5

3. ### How many even positive numbers are there?

In [118]:
evens_from_a = a[a % 2 == 0]
#evens_from_a

#a[a % 2==0]

print(len(a[(a > 0) & (a % 2 == 0)]))
# print(len(a[(is_positive) & (evens_from_a)]))
# also, why does the ampersand work but AND does not?

3


In [ ]:
positives = a[a > 0]
evens = positives[positives % 2 == 0]
evens

4. ### If you were to add 3 to each data point, how many positive numbers would there be?

In [119]:
#add_3 = [n +3 for n in a]
#add_3

b = a + 3
print(len(b[b > 0]))


10


In [120]:
#add_3 = [n +3 for n in a]
#add_3

5. ### If you squared each number, what would the new mean and standard deviation be?

In [121]:
print(np.square(a))
print(np.mean(np.square(a)))
print(np.std(np.square(a)))
print(f'Mean = {np.mean(np.square(a))}, StdDev = {np.std(np.square(a))}')

[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0
144.0243035046516
Mean = 74.0, StdDev = 144.0243035046516


6. ### A common statistical operation on a dataset is centering.
This means to adjust the data such that the mean of the data is 0.\
This is done by subtracting the mean from each data point.\
Center the data set.

In [129]:
print(np.mean(a))
# this creates a separate data set, where 3 is subtracted
c = a - 3
print(a)
print(c)
# this creates a separate data set

3.0
[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
[  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]


7. ### Calculate the z-score for each data point.
- Recall that the z-score is given by:

            Z=(x−μ)/σ


In [134]:
z = c/np.std(a)
print(z)



[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


8. #### Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

#### Life w/o numpy to life with numpy

##### Setup 1
 |||||||||||||||||||||| a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] ||||||||||||||||||||||

### Use python's built in functionality/operators to determine the following:
###### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

###### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

###### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

###### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

###### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

###### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

###### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

###### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 1.) - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(a)
print(f'Sum of a = {sum_of_a}')

# 2.) - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
print(f'Minimum of a = {min_of_a}')

# 3.) - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
print(f'Maximum of a = {max_of_a}')

# 4.) - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
print(f'Mean of a = {mean_of_a}')


# 5.) - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.product(a)
print(f'Product of a = {product_of_a}')

product_of_a = 1
for n in a:product_of_a *= n
    
product_of_a

# 6.) - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
print(f'Squares of a = {squares_of_a}')

squares_of_a = [n ** 2 for n in a]
squares_of_a

# 7.) - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a[a % 2 == 1]
print(f'Odds in a = {odds_in_a}')

# 8.) - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a % 2 == 0]
print(f'Evens in a = {evens_in_a}')

print('S e t u p     O n e       C O M P L E T E')


Sum of a = 55
Minimum of a = 1
Maximum of a = 10
Mean of a = 5.5
Product of a = 3628800
Squares of a = [  1   4   9  16  25  36  49  64  81 100]
Odds in a = [1 3 5 7 9]
Evens in a = [ 2  4  6  8 10]
S e t u p     O n e       C O M P L E T E



 What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
#### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
|||||||||||||||||||||| b = [ [3, 4, 5], [6, 7, 8] ] ||||||||||||||||||||||

###### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
```
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
```
###### Exercise 2 - refactor the following to use numpy. 
```
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
```
###### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
```
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
```

###### Exercise 4 - refactor the following using numpy to find the mean of b
```
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
```

###### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
```
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
```
###### Exercise 6 - refactor the following to use numpy to find the list of squares 
```
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
```

###### Exercise 7 - refactor using numpy to determine the odds_in_b
```
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
```

###### Exercise 8 - refactor the following to use numpy to filter only the even numbers
```
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
```
###### Exercise 9 - print out the shape of the array b.

###### Exercise 10 - transpose the array b.

###### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

###### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [5]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#             Hint, you'll first need to make sure that the "b" variable is a numpy array
#   sum_of_b = 0 for row in b: sum_of_b += sum(row)

b = ([[3, 4, 5], [6, 7, 8]])
b = np.array(b)

sum_of_b = 0 
for row in b: 
    sum_of_b += sum(row)

sum_of_b = b.sum()
print(f'Sum of b = {sum_of_b}')


# Exercise 2 - refactor the following to use numpy.
#     min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
        
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b = np.min(b)
print(f'Minimum of b = {min_of_b}')

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
#     max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b = b.max()
print(f'Maximum of b = {max_of_b}')

# maximum_b = np.max(b)the same. 


# Exercise 4 - refactor the following using numpy to find the mean of b
#.    mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(b)
print(f'Mean of b = {mean_of_b}')


# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#.    product_of_b = 1 for row in b: for number in row: product_of_b *= number

product_of_b = np.product(b)
print(f'Product of b = {product_of_b}')


# Exercise 6 - refactor the following to use numpy to find the list of squares
#.    squares_of_b = [] for row in b: for number in row: squares_of_b.append(number**2)

squares_of_b = np.square(b)
print(f'Squares of b = {squares_of_b}')


# Exercise 7 - refactor using numpy to determine the odds_in_b
#     odds_in_b = [] for row in b: for number in row: if(number % 2 != 0): odds_in_b.append(number)

odds_in_b = b[b % 2 == 1]
print(f'Odds in b = {odds_in_b}')


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
#     evens_in_b = [] for row in b: for number in row: if(number % 2 == 0): evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]
print(f'Evens in b = {evens_in_b}')

# Exercise 9 - print out the shape of the array b.

dimensions_of_b = np.shape(b)
print(f'The Shape of b = {dimensions_of_b}')


#Exercise 10 - transpose the array b.

transposed_b = np.transpose(b)
print(f'The Transposition of b = {transposed_b}')

b.T


#Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b_together = np.reshape(b, -1)
print(f'Reshaped b = {b_together}')

b.flatten()

b.reshape(1, 6)
b.reshape(6)

#Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1

b_apart = b.reshape(-1, 1)
print(f'Deshaped b = {b_apart}')

b.reshape(6, 1)




Sum of b = 33
Minimum of b = 3
Maximum of b = 8
Mean of b = 5.5
Product of b = 20160
Squares of b = [[ 9 16 25]
 [36 49 64]]
Odds in b = [3 5 7]
Evens in b = [4 6 8]
The Shape of b = (2, 3)
The Transposition of b = [[3 6]
 [4 7]
 [5 8]]
Reshaped b = [3 4 5 6 7 8]
Deshaped b = [[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3
# |||||||||||||||||||||| c = [ [1, 2, 3], [4, 5, 6], [7, 8, 9]] ||||||||||||||||||||||


HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
#### Exercise 1 - Find the min, max, sum, and product of c.

#### Exercise 2 - Determine the standard deviation of c.

#### Exercise 3 - Determine the variance of c.

#### Exercise 4 - Print out the shape of the array c

#### Exercise 5 - Transpose c and print out transposed result.

#### Exercise 6 - Get the dot product of the array c with c. 

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [11]:
c = [ [1, 2, 3], [4, 5, 6], [7, 8, 9]] 
c = np.array(c)

# Exercise 1 - Find the min, max, sum, and product of c.

min_c = np.min(c)
max_c = np.max(c)
sum_c = np.sum(c)
product_c = np.product(c)

print(f'Minimum of c = {min_c}, Maximum of c = {max_c}, Sum of c = {sum_c}, Product of c = {product_c}')

{
    "sum": c.sum(),
    "min": c.min(),
    "max": c.max(),
    "mean": c.mean(),
    "product": c.prod()
}
# ask if I can put this code on two lines without running into EOL error. 

# Exercise 2 - Determine the standard deviation of c.

std_c = np.std(c)
print(f'C has an STD = {std_c}')

# Exercise 3 - Determine the variance of c.

var_c = np.var(c)
print(f'Variance of C= {var_c}')

# Exercise 4 - Print out the shape of the array c

dimensions_of_c = np.shape(c)
print(f'The Shape of C = {dimensions_of_c}')


# Exercise 5 - Transpose c and print out transposed result.

transposed_c = np.transpose(c)
print(f'The Transposition of C = {transposed_c}')


# Exercise 6 - Get the dot product of the array c with c.

dot_product_c = np.dot(c, c)
print(f'Dot Product of C against C = {dot_product_c}')

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

two_six_one = c * np.transpose(c)
result = np.sum(two_six_one)
print(f'Sum Body onCe told me = {result}')

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400

long_boi = c * np.transpose(c)
product = np.prod(long_boi)
print(f'It is such a long way \n down = {product}')


Minimum of c = 1, Maximum of c = 9, Sum of c = 45, Product of c = 362880
C has an STD = 2.581988897471611
Variance of C= 6.666666666666667
The Shape of C = (3, 3)
The Transposition of C = [[1 4 7]
 [2 5 8]
 [3 6 9]]
Dot Product of C against C = [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Sum Body onCe told me = 261
It is such a long way 
 down = 131681894400


## Setup 4
# d = [[90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0],
# ||||||||[60, 45, -45, 90, -45, 180]]

#### Exercise 1 - Find the sine of all the numbers in d

#### Exercise 2 - Find the cosine of all the numbers in d

#### Exercise 3 - Find the tangent of all the numbers in d

#### Exercise 4 - Find all the negative numbers in d

#### Exercise 5 - Find all the positive numbers in d

#### Exercise 6 - Return an array of only the unique numbers in d.

#### Exercise 7 - Determine how many unique numbers there are in d.

#### Exercise 8 - Print out the shape of d.

#### Exercise 9 - Transpose and then print out the shape of d.

#### Exercise 10 - Reshape d into an array of 9 x 2

In [12]:
d = [[90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180]]
d = np.array(d)

# Exercise 1 - Find the sine of all the numbers in d

sine_d = np.sin(d)
print(f'Sine this d = {sine_d}')

# Exercise 2 - Find the cosine of all the numbers in d

cosine_d = np.cos(d)
print(f'Cosine this d = {cosine_d}')

# Exercise 3 - Find the tangent of all the numbers in d

tangent_d = np.tan(d)
print(f'Tan this d = {tangent_d}')

# Exercise 4 - Find all the negative numbers in d

neg_d = d < 0
print(f' What a negative D = {d[neg_d]}')

# Exercise 5 - Find all the positive numbers in d

pos_d = d > 0
print(f' Such a positive D = {d[pos_d]}')


# Exercise 6 - Return an array of only the unique numbers in d.

unique_d = np.unique(d)
print(f' What a unique D = {unique_d}')

# Exercise 7 - Determine how many unique numbers there are in d.

unique_d = np.unique(d)
print(len(unique_d))
print('ah, the number of unique d is exquisite')


# Exercise 8 - Print out the shape of d.

dimensions_of_d = np.shape(d)
print(f'The Impressive Shape of D = {dimensions_of_d}')


# Exercise 9 - Transpose and then print out the shape of d.

transposed_d = np.transpose(d)
print(f'The Transposition of D = {transposed_d}')


# Exercise 10 - Reshape d into an array of 9 x 2

d_apart = d.reshape(-1, 2)
print(f'Deshaped D = {d_apart}')

Sine this d = [[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]
Cosine this d = [[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]
Tan this d = [[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]
 What a negative D = [-90 -30 -45 -45]
 Such a positive D = [ 90  30  45 120 180  45 270  90  60  45  90 180]
 What a unique D = [-90 -45 -30   0  30  45  60  90 120 180 270]
11
ah, the number of unique d is exquisite
The Impressive Shape of D = (3, 6)
The Transposition of D = [